### ISSUE TITLE
Wrong extension-key in composer.json

### ISSUE THREAD

**Issue by NatalieKH** [TYPO3GmbH/svg_sanitizer#1]
```
    "extra": {
        "typo3/cms": {
            "extension-key": "svg_sanitize",
            "web-dir": ".build"
        }
    },
```

should be 

```
    "extra": {
        "typo3/cms": {
            "extension-key": "svg_sanitizer",
            "web-dir": ".build"
        }
    },
```

**Comment by fsuter** [comment]
Indeed! This actually makes the update wizard crash, because it checks if extension "svg_sanitizer" is loaded. The code is:
`$extensionBasePath = ExtensionManagementUtility::extPath('svg_sanitizer');`
in `SvgSanitizerService` on line 64.
